#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSpeechSegment.h"
#import "SystranSpeechSpeaker.h"
#import "SystranSpeechChannel.h"
#import "SystranErrorResponse.h"


@protocol SystranSpeechSegmentResponse
@end

@interface SystranSpeechSegmentResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of channels 
 */
@property(nonatomic) NSArray<SystranSpeechChannel>* channels;
/* Array of speakers 
 */
@property(nonatomic) NSArray<SystranSpeechSpeaker>* speakers;
/* Array of segments 
 */
@property(nonatomic) NSArray<SystranSpeechSegment>* segments;

@end
