#import <Foundation/Foundation.h>
#import "SystranImageAnalyzeLayoutResponse.h"
#import "SystranImageAnalyzeRegionResponse.h"
#import "SystranSupportedLanguagesResponse.h"
#import "SystranImageTranscribeResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranImageApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranImageApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranImageApi*) sharedAPI;
///
///
/// Image layout analysis
/// Analyze the layout of an image.
///
/// @param imageFile Image file
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranImageAnalyzeLayoutResponse*
-(NSNumber*) multimodalImageAnalyzeLayoutPostWithCompletionBlock :(NSURL*) imageFile 
     lang:(NSString*) lang 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranImageAnalyzeLayoutResponse* output, NSError* error))completionBlock;
    


///
///
/// Image region analysis
/// Analyze the region properties of an image.
///
/// @param imageFile Image file
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranImageAnalyzeRegionResponse*
-(NSNumber*) multimodalImageAnalyzeRegionPostWithCompletionBlock :(NSURL*) imageFile 
     lang:(NSString*) lang 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranImageAnalyzeRegionResponse* output, NSError* error))completionBlock;
    


///
///
/// Supported Languages
/// List of languages in which Image processing is supported.
///
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranSupportedLanguagesResponse*
-(NSNumber*) multimodalImageSupportedLanguagesGetWithCompletionBlock :(NSString*) callback 
    
    completionHandler: (void (^)(SystranSupportedLanguagesResponse* output, NSError* error))completionBlock;
    


///
///
/// Image text transcription
/// Transcribe text from an image.
///
/// @param imageFile Image file
/// @param lang Language code of the input ([details](#description_langage_code_values))
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranImageTranscribeResponse*
-(NSNumber*) multimodalImageTranscribePostWithCompletionBlock :(NSURL*) imageFile 
     lang:(NSString*) lang 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranImageTranscribeResponse* output, NSError* error))completionBlock;
    



@end
