#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranErrorResponse.h"


@protocol SystranFileExtractTextResponse
@end

@interface SystranFileExtractTextResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Text extracted from the input 
 */
@property(nonatomic) NSString* text;
/* Format of the input 
 */
@property(nonatomic) NSString* format;

@end
