#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranSpeechWord
@end

@interface SystranSpeechWord : SystranObject

/* Start time (in seconds) 
 */
@property(nonatomic) NSNumber* start;
/* Duration (in seconds) 
 */
@property(nonatomic) NSNumber* duration;
/* Confidence 
 */
@property(nonatomic) NSNumber* confidence;
/* Word text 
 */
@property(nonatomic) NSString* text;

@end
