#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSpeechLangSegment.h"
#import "SystranSpeechLangSpeaker.h"
#import "SystranSpeechChannel.h"
#import "SystranErrorResponse.h"


@protocol SystranSpeechDetectLanguageResponse
@end

@interface SystranSpeechDetectLanguageResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of channels 
 */
@property(nonatomic) NSArray<SystranSpeechChannel>* channels;
/* Array of speakers 
 */
@property(nonatomic) NSArray<SystranSpeechLangSpeaker>* speakers;
/* Array of segments 
 */
@property(nonatomic) NSArray<SystranSpeechLangSegment>* segments;

@end
