#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranImageText
@end

@interface SystranImageText : SystranObject

/* Text 
 */
@property(nonatomic) NSString* text;
/* Confidence 
 */
@property(nonatomic) NSNumber* confidence;

@end
