#import <Foundation/Foundation.h>
#import "SystranFileExtractTextResponse.h"
#import "SystranFileSupportedFormatsResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranFileApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranFileApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranFileApi*) sharedAPI;
///
///
/// Extract text from a file
/// Extract text from a file.
///
/// @param inputFile Input File
/// @param lang Language code of the input ([details](#description_langage_code_values)) or `auto` for automatic detection
/// @param format Format of the input file.\n\nValid values are the mimetypes returned by the supportedFormats service.
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranFileExtractTextResponse*
-(NSNumber*) multimodalFileExtractTextPostWithCompletionBlock :(NSURL*) inputFile 
     lang:(NSString*) lang 
     format:(NSString*) format 
     profile:(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranFileExtractTextResponse* output, NSError* error))completionBlock;
    


///
///
/// Supported file formats
/// Get a list of supported file formats.
///
/// @param profile Profile id
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranFileSupportedFormatsResponse*
-(NSNumber*) multimodalFileSupportedFormatsGetWithCompletionBlock :(NSNumber*) profile 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranFileSupportedFormatsResponse* output, NSError* error))completionBlock;
    



@end
