#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranImageBox.h"
#import "SystranErrorResponse.h"


@protocol SystranImageAnalyzeLayoutResponse
@end

@interface SystranImageAnalyzeLayoutResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of boxes 
 */
@property(nonatomic) NSArray<SystranImageBox>* boxes;

@end
