#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranSpeechSpeaker
@end

@interface SystranSpeechSpeaker : SystranObject

/* Speaker id 
 */
@property(nonatomic) NSString* _id;
/* Channel id 
 */
@property(nonatomic) NSNumber* channel;
/* Speech duration (in seconds) 
 */
@property(nonatomic) NSNumber* duration;
/* Gender 
 */
@property(nonatomic) NSString* gender;

@end
