#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranFileFormat
@end

@interface SystranFileFormat : SystranObject

/* Mimetype 
 */
@property(nonatomic) NSString* mimetype;
/* Friendly Name 
 */
@property(nonatomic) NSString* name;

@end
