#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranImagePosition
@end

@interface SystranImagePosition : SystranObject


@property(nonatomic) NSNumber* x;

@property(nonatomic) NSNumber* y;

@end
