#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranSpeechChannel.h"
#import "SystranErrorResponse.h"
#import "SystranSpeechAlignSegment.h"


@protocol SystranSpeechAlignResponse
@end

@interface SystranSpeechAlignResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Array of channels 
 */
@property(nonatomic) NSArray<SystranSpeechChannel>* channels;
/* Array of segments 
 */
@property(nonatomic) NSArray<SystranSpeechAlignSegment>* segments;

@end
