#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranImageSize
@end

@interface SystranImageSize : SystranObject


@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@end
