#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranFileFormat.h"
#import "SystranErrorResponse.h"


@protocol SystranFileSupportedFormatsResponse
@end

@interface SystranFileSupportedFormatsResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* List of supported formats 
 */
@property(nonatomic) NSArray<SystranFileFormat>* formats;

@property (nonatomic) NSString* mimetype;

@end
