#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranSpeechChannel
@end

@interface SystranSpeechChannel : SystranObject

/* Channel id 
 */
@property(nonatomic) NSNumber* _id;
/* Signal duration (in seconds) 
 */
@property(nonatomic) NSNumber* signalDuration;
/* Speech duration (in seconds) 
 */
@property(nonatomic) NSNumber* speechDuration;

@end
