#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranSpeechLangSpeaker
@end

@interface SystranSpeechLangSpeaker : SystranObject

/* Speaker id 
 */
@property(nonatomic) NSString* _id;
/* Channel id 
 */
@property(nonatomic) NSNumber* channel;
/* Speech duration (in seconds) 
 */
@property(nonatomic) NSNumber* duration;
/* Gender 
 */
@property(nonatomic) NSString* gender;
/* Speaker detected language ([details](#description_langage_code_values)) 
 */
@property(nonatomic) NSString* lang;
/* Confidence for the detected language 
 */
@property(nonatomic) NSNumber* langConfidence;

@end
