#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranImageSize.h"
#import "SystranImagePosition.h"


@protocol SystranImageBox
@end

@interface SystranImageBox : SystranObject


@property(nonatomic) SystranImagePosition* position;

@property(nonatomic) SystranImageSize* size;

@end
